#!/usr/bin/env bash
# script transfers file from client to server

# check if required arguments are all there
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1

fi

# run command
scp -o StrictHostKeyChecking=no "$1" "$3@$2:$4"
