#!/usr/bin/env bash
# script to install nginx web server

#install nginx on server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

#configure web server
sudo mkdir -p /var/www/test.com/html
sudo chown -R "$USER":"$USER" /var/www/example.com/html
sudo touch /var/www/test.com/html/index.html
echo "Hello World!" | sudo tee /var/www/test.com/index.html
printf %s "server {
     listen      80;
     listen      [::]:80;
     root        /var/www/example.com/html;
     index       index.html index.htm;
     server_name example.com;
     location / {
              try_files @$uri $uri/ =404;
     }
}" | sudo tee /etc/nginx/sites-available/test.com
sudo ln -s /etc/nginx/sites-available/test.com /etc/nginx/sites-enabled/

sudo service nginx restart
