#!/usr/bin/env bash
# configures load balancer for the 2 servers

sudo apt-get -y update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.7
sudo apt-get install haproxy=2.7.\*
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 190062-web-01 34.224.63.152  check\n\tserver 190062-web-02 100.25.12.227 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
