#!/usr/bin/env bash
# installs and configures load balancer for 2 web servers

sudo apt-get -y update
sudo apt-get install -y haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver web-01 34.224.63.152  check\n\tserver web-02 100.25.12.227 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
