#!/usr/bin/env bash
# web stack debugging for port 80 listening, and nginx must be running

sudo apt update
sudo apt install net-tools curl -y
existing_process=$(sudo netstat -tuln | grep ':80')
if [ -n "$existing_process" ]; then
  existing_pid=$(echo "$existing_process" | awk '{print $7}' | awk -F '/' '{print $1}')
  sudo kill -9 "$existing_pid"
fi
sudo apt install nginx -y
nginx_status=$(sudo systemctl status nginx)
if [[ $nginx_status == *"active (running)"* ]]; then
  sudo systemctl restart nginx
else
  sudo systemctl start nginx
fi
sudo sed -i 's/listen 80;/listen 80 default_server;/' /etc/nginx/sites-available/default
sudo nginx -t
sudo systemctl restart nginx
sudo netstat -tuln | grep ':80'
