#!/usr/bin/env bash
# Prints "Best School" to  display 10 times
# at index 9 also adds "Hi" in new line

i=1
while [ $i -le 10 ];
do
    if [ $i -eq 9 ]
    then
       echo "Best School"
       echo "Hi"
    else
    echo  "Best School"
    fi
    i=$((i + 1))
done
