#!/usr/bin/env bash
# script displayhs numbers from 1 to 20
# displays a message when the number is 4, 9 or 17
e=1
while [ $e -le 20 ]
do
    echo "$e"
    case $e in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((e++))
done
