#!/usr/bin/env bash
# script checks for file information
if [ -e "school" ]; then
  echo "school file exists"
else
  echo "school file does not exist"
  exit 1
fi

if [ ! -s "school" ]; then
  echo "school file is empty"
else
  echo "school file is not empty"
fi


if [ -f "school" ]; then
  echo "school is a regular file"
fi
