#!/usr/bin/env bash
# script that gets Apache to run on the container and to return a page containing Hello Holberton when querying the root of it
apt-get update
apt-get -y install apache2

sudo mkdir /var/www/html
sudo touch /var/www/html/index.html
echo "Hello Holberton!" | sudo tee /var/www/html/index.html

service apache2 restart
