#!/usr/bin/env bash
# Gracefully reloads Gunicorn.

pids=$(pgrep gunicorn)

if [ -n "$pids" ]; then
    echo "Reloading Gunicorn processes: $pids"
    for pid in $pids; do
        kill -HUP "$pid"
    done
else
    echo "No Gunicorn processes found."
fi
